// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package go_micro_service_dbproxy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SingleAction struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params               []byte   `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleAction) Reset()         { *m = SingleAction{} }
func (m *SingleAction) String() string { return proto.CompactTextString(m) }
func (*SingleAction) ProtoMessage()    {}
func (*SingleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *SingleAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleAction.Unmarshal(m, b)
}
func (m *SingleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleAction.Marshal(b, m, deterministic)
}
func (m *SingleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleAction.Merge(m, src)
}
func (m *SingleAction) XXX_Size() int {
	return xxx_messageInfo_SingleAction.Size(m)
}
func (m *SingleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleAction.DiscardUnknown(m)
}

var xxx_messageInfo_SingleAction proto.InternalMessageInfo

func (m *SingleAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SingleAction) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type ReqExec struct {
	Sequence             bool            `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Transaction          bool            `protobuf:"varint,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ResultType           int32           `protobuf:"varint,3,opt,name=resultType,proto3" json:"resultType,omitempty"`
	Action               []*SingleAction `protobuf:"bytes,4,rep,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqExec) Reset()         { *m = ReqExec{} }
func (m *ReqExec) String() string { return proto.CompactTextString(m) }
func (*ReqExec) ProtoMessage()    {}
func (*ReqExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *ReqExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqExec.Unmarshal(m, b)
}
func (m *ReqExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqExec.Marshal(b, m, deterministic)
}
func (m *ReqExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqExec.Merge(m, src)
}
func (m *ReqExec) XXX_Size() int {
	return xxx_messageInfo_ReqExec.Size(m)
}
func (m *ReqExec) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqExec.DiscardUnknown(m)
}

var xxx_messageInfo_ReqExec proto.InternalMessageInfo

func (m *ReqExec) GetSequence() bool {
	if m != nil {
		return m.Sequence
	}
	return false
}

func (m *ReqExec) GetTransaction() bool {
	if m != nil {
		return m.Transaction
	}
	return false
}

func (m *ReqExec) GetResultType() int32 {
	if m != nil {
		return m.ResultType
	}
	return 0
}

func (m *ReqExec) GetAction() []*SingleAction {
	if m != nil {
		return m.Action
	}
	return nil
}

type RespExec struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespExec) Reset()         { *m = RespExec{} }
func (m *RespExec) String() string { return proto.CompactTextString(m) }
func (*RespExec) ProtoMessage()    {}
func (*RespExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *RespExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespExec.Unmarshal(m, b)
}
func (m *RespExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespExec.Marshal(b, m, deterministic)
}
func (m *RespExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespExec.Merge(m, src)
}
func (m *RespExec) XXX_Size() int {
	return xxx_messageInfo_RespExec.Size(m)
}
func (m *RespExec) XXX_DiscardUnknown() {
	xxx_messageInfo_RespExec.DiscardUnknown(m)
}

var xxx_messageInfo_RespExec proto.InternalMessageInfo

func (m *RespExec) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespExec) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RespExec) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SingleAction)(nil), "go.micro.service.dbproxy.SingleAction")
	proto.RegisterType((*ReqExec)(nil), "go.micro.service.dbproxy.ReqExec")
	proto.RegisterType((*RespExec)(nil), "go.micro.service.dbproxy.RespExec")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x4d, 0x43, 0x7a, 0x09, 0x08, 0x79, 0x40, 0x51, 0x07, 0x14, 0x32, 0xa0, 0x4c,
	0x1e, 0xca, 0xc6, 0x80, 0x04, 0x2a, 0x3b, 0xba, 0x32, 0xb0, 0xba, 0xce, 0x29, 0x0a, 0x6a, 0xe2,
	0xd4, 0x76, 0x50, 0xfb, 0x44, 0xbc, 0x26, 0x8a, 0x13, 0x50, 0x96, 0xb2, 0xfd, 0x77, 0xbe, 0xbb,
	0xff, 0xbb, 0x33, 0x44, 0xad, 0x56, 0x87, 0x23, 0x6f, 0xb5, 0xb2, 0x8a, 0x25, 0xa5, 0xe2, 0x75,
	0x25, 0xb5, 0xe2, 0x86, 0xf4, 0x57, 0x25, 0x89, 0x17, 0x5b, 0xf7, 0x9e, 0x3d, 0x42, 0xbc, 0xa9,
	0x9a, 0x72, 0x47, 0xcf, 0xd2, 0x56, 0xaa, 0x61, 0x0c, 0xfc, 0x46, 0xd4, 0x94, 0x78, 0xa9, 0x97,
	0x2f, 0xd0, 0x69, 0x76, 0x03, 0x41, 0x2b, 0xb4, 0xa8, 0x4d, 0x72, 0x9e, 0x7a, 0x79, 0x8c, 0x63,
	0x94, 0x7d, 0x7b, 0x70, 0x81, 0xb4, 0x7f, 0x3d, 0x90, 0x64, 0x4b, 0x08, 0x0d, 0xed, 0x3b, 0x6a,
	0xe4, 0xd0, 0x1b, 0xe2, 0x5f, 0xcc, 0x52, 0x88, 0xac, 0x16, 0x8d, 0x11, 0xce, 0xc2, 0x0d, 0x09,
	0x71, 0x9a, 0x62, 0xb7, 0x00, 0x9a, 0x4c, 0xb7, 0xb3, 0xef, 0xc7, 0x96, 0x92, 0x59, 0xea, 0xe5,
	0x73, 0x9c, 0x64, 0xd8, 0x13, 0x04, 0x63, 0xb3, 0x9f, 0xce, 0xf2, 0x68, 0x75, 0xcf, 0x4f, 0x2d,
	0xc4, 0xa7, 0xdb, 0xe0, 0xd8, 0x95, 0xad, 0x21, 0x44, 0x32, 0xad, 0x23, 0x65, 0xe0, 0x4b, 0x55,
	0x0c, 0x94, 0x73, 0x74, 0x9a, 0x5d, 0xc3, 0xac, 0x36, 0xa5, 0x23, 0x5b, 0x60, 0x2f, 0xfb, 0xaa,
	0x42, 0x58, 0xe1, 0x58, 0x62, 0x74, 0x7a, 0xf5, 0x09, 0x57, 0xeb, 0x97, 0xb7, 0xde, 0x65, 0x33,
	0x98, 0xb2, 0x0f, 0xb8, 0xec, 0x67, 0x76, 0xf6, 0xf7, 0x7c, 0x77, 0xa7, 0xc1, 0xc6, 0x4b, 0x2d,
	0xb3, 0xff, 0x4a, 0x06, 0xc6, 0xec, 0x6c, 0x1b, 0xb8, 0x8f, 0x7b, 0xf8, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x62, 0x76, 0xe7, 0xc7, 0x01, 0x00, 0x00,
}
