// Code generated by protoc-gen-go. DO NOT EDIT.
// source: download.proto

package go_micro_service_download

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqEntry struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEntry) Reset()         { *m = ReqEntry{} }
func (m *ReqEntry) String() string { return proto.CompactTextString(m) }
func (*ReqEntry) ProtoMessage()    {}
func (*ReqEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{0}
}

func (m *ReqEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEntry.Unmarshal(m, b)
}
func (m *ReqEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEntry.Marshal(b, m, deterministic)
}
func (m *ReqEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEntry.Merge(m, src)
}
func (m *ReqEntry) XXX_Size() int {
	return xxx_messageInfo_ReqEntry.Size(m)
}
func (m *ReqEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEntry proto.InternalMessageInfo

type RespEntry struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entry                string   `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespEntry) Reset()         { *m = RespEntry{} }
func (m *RespEntry) String() string { return proto.CompactTextString(m) }
func (*RespEntry) ProtoMessage()    {}
func (*RespEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{1}
}

func (m *RespEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespEntry.Unmarshal(m, b)
}
func (m *RespEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespEntry.Marshal(b, m, deterministic)
}
func (m *RespEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespEntry.Merge(m, src)
}
func (m *RespEntry) XXX_Size() int {
	return xxx_messageInfo_RespEntry.Size(m)
}
func (m *RespEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RespEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RespEntry proto.InternalMessageInfo

func (m *RespEntry) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RespEntry) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqEntry)(nil), "go.micro.service.download.ReqEntry")
	proto.RegisterType((*RespEntry)(nil), "go.micro.service.download.RespEntry")
}

func init() { proto.RegisterFile("download.proto", fileDescriptor_f7ce52b48c9eea83) }

var fileDescriptor_f7ce52b48c9eea83 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0x2f, 0xcf,
	0xcb, 0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4c, 0xcf, 0xd7, 0xcb,
	0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x83, 0x29, 0x50,
	0xe2, 0xe2, 0xe2, 0x08, 0x4a, 0x2d, 0x74, 0xcd, 0x2b, 0x29, 0xaa, 0x54, 0xf2, 0xe7, 0xe2, 0x0c,
	0x4a, 0x2d, 0x2e, 0x00, 0x73, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4,
	0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x84, 0x8b, 0x35, 0x15, 0xa4,
	0x4d, 0x82, 0x19, 0x2c, 0x0e, 0xe1, 0x18, 0xe5, 0x73, 0xf1, 0xbb, 0x40, 0x2d, 0x0a, 0x86, 0x58,
	0x2c, 0x14, 0xc3, 0xc5, 0x0b, 0x13, 0x82, 0xd8, 0xa3, 0xac, 0x87, 0xd3, 0x71, 0x7a, 0x30, 0x97,
	0x49, 0xa9, 0xe0, 0x55, 0x04, 0x75, 0xb2, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xbf, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x41, 0x36, 0x4a, 0x64, 0x01, 0x01, 0x00, 0x00,
}
